version: "3.8"

services:
  react-app:
    build:
      context: . # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile # Optional: Specify the Dockerfile name
    container_name: devops-build-task
    ports:
      - "80:80"
    restart: unless-stopped
